workflows:
  android-build:
    name: Flutter Android CI

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    environment:
      flutter: stable

    scripts:
    - name: Create .env file
      script: |
        echo "GROQ_API_KEY=$GROQ_API_KEY" > .env
        echo "GEMINI_API_KEY=$GEMINI_API_KEY" >> .env

        echo "Checking .env..."
        pwd
        ls -la
        cat .env

    - name: Install dependencies
      script: flutter pub get

    - name: Analyze
      script: flutter analyze

    - name: Build APK
      script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk